### ISSUE TITLE
Unable to build blab due to owl failing unit tests

### ISSUE THREAD

**Issue by brarcher** [aoh/blab#1]
Perhaps to https://github.com/aoh/radamsa/issues/5 in Radamsa, blab seems to be unable to build due to the version of owl being used (the latest) either not being compatible or currently has failing unit tests on OSX. Example:

```
$ git clone https://github.com/aoh/blab.git
...
$ cd blab
$ make
...
# check that the new image passes tests
CC=cc tests/run all bin/vm fasl/bootp.fasl
-n Running tests/ against bin/vm fasl/bootp.fasl:
 o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o oERROR: tests/dir.scm
1c1
< (dir.scm)

---
> (xkdir.scm dir.scm)
ERROR: tests/dir.scm
make[2]: *** [fasl/ol.fasl] Error 1
make[1]: *** [get-owl] Error 2
make: *** [blab.c] Error 2
```

Consider using a tagged version of owl for blab.

**Comment by aoh** [comment]
Thanks. I forgot to include changes to one file in the last owl commit. I'll switch to using a fixed version of owl when the next version is tagged.
